project:
  type: book

book:
  title: "example_book"
  author: "Jane Doe"
  date: "2023-03-03"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  epub:
    toc:
      true
    date:
      "2023-03-03"